### ISSUE TITLE
DayOffset is not modeled for ServiceJourney

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#13]
Unlike the Call and datedPassingTimes model the ServiceJourney lacks the ability to define a DayOffset. Is this something missing in the standard, or how should it be modelled instead?

https://github.com/nick-knowles/NeTEx-XML/blob/master/schema/1.03/xsd/netex_part_2/part2_journeyTimes/netex_serviceJourney_version-v1.0.xsd#L223

Use case: I want to communicate a trip operating from 24:00:01 to 24:30:00 on the previous operating day.

**Comment by Aurige** [comment]
I'm missing your point. The ServiceJourney  contains either Calls either PassingTimes bothe having the DayOffset, as you pointed.
cf:
_ServiceJourney:[ServiceJourneyGroup]:[VehicleJourneyTimesGroup]:passingTimes
ServiceJourney:[ServiceJourneyGroup]:[ServiceJourneyPartsGroup]:calls_

Only the generic information of  _ServiceJourney:[ServiceJourneyGroup]:[ServiceTimeGroup]:DepartureTime_ doesn't have a _DayOffset_ but it can be complemented (or eve replaced) by the first _PassingTime_ or _Call_.

**Comment by skinkie** [comment]
We are not using passTimes or Calls. We are refering DepartureTime as an offset for the TimeDemandTypeRef.

``` xml
<ServiceJourney version="any" id="HTM:ServiceJourney:001">
    <validityConditions>
        <AvailabilityConditionRef ref="HTM:AvailabilityCondition:Zondagen"/>
    </validityConditions>
    <TypeOfProductCategoryRef ref="BISON:TypeOfProductCategory:7"/>
    <DepartureTime>01:21:00</DepartureTime>
    <JourneyPatternRef nameOfRefClass="ServiceJourneyPattern" ref="HTM:ServiceJourneyPattern:001"/>
    <TimeDemandTypeRef version="any" ref="HTM:TimeDemandType:001"/>
    <BlockRef version="any" ref="HTM:Block:001"/>
</ServiceJourney>
```

**Comment by Aurige** [comment]
Ok
A workaround is to provide just the first passing time or call (so just one). Another is to have a dedicated Daytype (but that's probably not what you want).
A nicer way, if there is no urgency, is to take advantage of the NeTEx group reactivation to review Part 1/2 and add a DayOffset here (the draft scope has been circulated to the group, did you get it, probably from Jan ?)

**Comment by skinkie** [comment]
I am not in to the business of quick-and-dirty workarounds.

As long the NeTEx group is not an open forum with open invitations and open documents nobody gets those.

**Comment by Aurige** [comment]
You are right it is "not ideal" since an additional DayOffset would obviously be the easier way for you.
As you know I don't have hand on the CEN process of managing groups, but we do try to keep it as open as possible. I can add you to our mailing list if you want, and you are welcome to attend some of our meetings (if not all, if this is Ok with Jan).

**Comment by JanTijmensen** [comment]
Hello Christophe,
It is ok with me to add Stefan to the mailing list. While you at it please add my college  Henno Willering (Willering@connekt.nlmailto:Willering@connekt.nl).

Regards,

Jan Tijmensen [Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: cid:image001.png@01CDA86C.62545240]  Documentalist BISON [Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: cid:image001.png@01CDA86C.62545240]  Connekt/ITS Netherlandshttp://www.connekt.nl/ [Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: cid:image001.png@01CDA86C.62545240]  tijmensen@connekt.nlmailto:tijmensen@connekt.nl [Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: cid:image001.png@01CDA86C.62545240]  + 31 15 251 65 65 office [Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: cid:image001.png@01CDA86C.62545240]  + 31 6 100 79 237 mobile
You can follow us on
[Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: cid:image011.png@01CDA86B.EAC6DA40]http://www.connekt.nl/[Beschrijving: Beschrijving: http://service.marketingmonday.nl/public/project/c0d9cc79b2803027d02eae77589822c7/twitter_2.png]https://twitter.com/#!/ConnektNL [Beschrijving: Beschrijving: http://service.marketingmonday.nl/public/project/c0d9cc79b2803027d02eae77589822c7/linkedin_2.png] http://www.linkedin.com/company/73317?trk=tyah  P  Please consider the environment before printing this e-mail [Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: Beschrijving: cid:image001.png@01CDA86C.62545240]  Disclaimerhttp://www.connekt.nl/nl-NL/disclaimer/

Van: Christophe Duquesne [mailto:notifications@github.com]
Verzonden: donderdag 20 oktober 2016 11:07
Aan: nick-knowles/NeTEx-XML
Onderwerp: Re: [nick-knowles/NeTEx-XML] DayOffset is not modeled for ServiceJourney (#13)

You are write, but "quick-and-dirty" was just a turn of phrase here, mainly meening "not ideal" since an additional DayOffset would obviusly be the easier way for you.
As you know I don't have hand on the CEN process of managing groups, but we do try to keep it as open as possible. I can add you to our mailing list if you want, and you are welcome to attend some of our meetings (if not all, if this is Ok with Jan).

**Comment by skinkie** [comment]
https://github.com/nick-knowles/NeTEx-XML/blob/master/schema/1.03/xsd/netex_part_2/part2_journeyTimes/netex_journeyDesignator_support-v1.0.xsd#L124

**Comment by skinkie** [comment]
``` diff
diff --git a/xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version-v1.0.xsd b/xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version-v1.0.xsd
index 442a1ee..0407a88 100644
--- a/xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version-v1.0.xsd
+++ b/xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version-v1.0.xsd
@@ -248,6 +248,11 @@ Rail transport, Roads and Road transport
                    <xsd:documentation>Time of departure.</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
+           <xsd:element name="DepartureDayOffset" type="DayOffsetType" default="0" minOccurs="0">
+               <xsd:annotation>
+                   <xsd:documentation>Number of days after the starting departure time of the journey if  not same calendar day. Default is 0 for same day.</xsd:documentation>
+               </xsd:annotation>
+           </xsd:element>
            <xsd:element name="Frequency" type="FrequencyStructure" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Frequency of Journey.</xsd:documentation>
```

**Comment by Aurige** [comment]
You are right, things should be aligned

**Comment by skinkie** [comment]
Not only that. I noticed that even the XSD restrictions for DayOffset style data are not all using DayOffsetType.

**Comment by nick-knowles** [comment]
Fixed 2018
