### ISSUE TITLE
XSD validation of Examples

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#9]
Quite a few examples do not validate with the current NeTEx XSD an example is Netex_CDL1_Bus_Zonal_MobileProducts.xml Could they be updated?

**Comment by Aurige** [comment]
Hi Stefan 
I first would like to apologize for the very slow answer. We are currently in the middle of the phase between the end of the CEN standardization process, and the beginning of a more traditional maintenance phase (outside of CEN, so a new organization has to be started). We will have a set of meeting in June and hope that we will end with a much more reactive process (anyway I'm afraid it can't be less reactive :-( ).

To be back to your question, the file you are pointing is a kind of "dead file" since it is not in the XML Spy project we use to manage the full XSD (the .spp file). So either we delete it, either if it is of a specific use for you, we can try to update it and reintegrate in the official examples.

**Comment by skinkie** [comment]
There is really a need for good examples for other countries making profiles.

**Comment by Aurige** [comment]
Yes you are fully right... I'm currently pushing to try to go in that direction at European level
By the way, have you check the ongoing great Norwegian work on profiles: https://rutebanken.atlassian.net/wiki/display/PUBLIC/NeTEx+profil+Norge

**Comment by skinkie** [comment]
Wanna see the Dutch one we collaborated on? :)

**Comment by Aurige** [comment]
Yes, of course if it is open !

**Comment by skinkie** [comment]
https://gist.github.com/skinkie/b05998d2b6bfc4509000d9a93884e08c

**Comment by Aurige** [comment]
Thanks !
Are you defining a kind of simplified NeTEx compatible schema ?
The concept selection looks "operation oriented" (blocks, runtimes, time demand type, activation point, etc.)

**Comment by skinkie** [comment]
In The Netherlands for @BISONNL the first objective is to define a NeTEx profile which is compatible with the current timetable exchange. We have defined a normalised format, with an explicit calendar as bitstring. After its adoption we will focus towards versioning of this information. For fare exchange a previous version of NeTEx has been used, so this standard should be updated as well.

Because of the speed of development I have crafted a XSD which validates in milliseconds, and allows to focus on the minimum required set of attributes in the Dutch Profile. It is completely compatible with the NeTEx schema.

**Comment by Aurige** [comment]
Sounds clever !
I saw the use of ValidDayBits for "calendar bitstring"
Yes BISON was one of the great contibutor to NeTEx Part 3 with its first fare implementation
Please keep me informed of progress, this is very interesting, and it is very helpfull to see how NeTEx is used (and what we needs to be improved, fixed, set up, etc.)

**Comment by skinkie** [comment]
We have also an almost publication worthy Dutch NeTEx profile export for Giro Hastus. I am positive that such interfaces will really benefit global adoption.

**Comment by Aurige** [comment]
Yes ! I know a lot of countries, authorities and companies that would love to have this !
